#输出结果放置docs文件夹内
destination: docs
#插件
plugins:
  - jekyll-paginate

# 使用 kramdown 作为 Markdown 解析器
markdown: kramdown
# 启用 MathJax 支持（部分主题需此配置）
mathjax: true

#css文件调用路径
sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed
  
# 启用分页功能
paginate: 4
paginate_path: "/page:num/"

# 专栏配置
category_list:
  - name: "电机控制"
    category: motorcontrol
    url: "/motorcontrol"
    stats: true
    
  #- name: "电动飞机"
  #  category: electricalplane
  #  url: "/electricalplane"
  #  stats: true
    
  #- name: "读书笔记"
  #  category: reading
  # url: "/reading"
  #  stats: true

#导航栏设置
navigation:
  - name: "首页"
    url: "/"
  - name: "电机控制"
    url: "/motorcontrol"
  #- name: "电动飞机"
  #  url: "/electricalplane"
  #- name: "读书笔记"
  #  url: "/reading"
  #- name: "关于"
  #  url: "/about"

# 个人信息
author:
  name: Feili
  avatar: /assets/images/avatar.jpg
  bio: 努力学习，天天向上
  contacts:
    email: 420848172@qq.com
    github: feilichen777.github.io